import type { AlgorithmCatalogItem } from "../types";

// Catalog of 9 built-in machine learning algorithms matching Figma design
export const ALGORITHMS_CATALOG: AlgorithmCatalogItem[] = [
  {
    id: "linear-regression",
    name: "Linear Regression",
    shortName: "linear",
    className: "LinearRegression",
    type: "regression",
    category: "builtin",
    description: "Linear model for regression problems",
    hyperparameters: [
      {
        name: "fit_intercept",
        label: "Fit Intercept",
        type: "select",
        defaultValue: true,
        options: [
          { label: "True", value: true },
          { label: "False", value: false },
        ],
      },
      {
        name: "normalize",
        label: "Normalize",
        type: "select",
        defaultValue: false,
        options: [
          { label: "True", value: true },
          { label: "False", value: false },
        ],
      },
    ],
  },
  {
    id: "ridge-regression",
    name: "Ridge Regression",
    shortName: "ridge",
    className: "Ridge",
    type: "regression",
    category: "builtin",
    description: "Linear regression with L2 regularization",
    hyperparameters: [
      {
        name: "alpha",
        label: "Alpha",
        type: "number",
        defaultValue: 1.0,
        placeholder: "Ex. 0.5",
        required: true,
      },
      {
        name: "fit_intercept",
        label: "Fit Intercept",
        type: "select",
        defaultValue: true,
        options: [
          { label: "True", value: true },
          { label: "False", value: false },
        ],
      },
      {
        name: "solver",
        label: "Solver",
        type: "select",
        defaultValue: "auto",
        options: [
          { label: "Auto", value: "auto" },
          { label: "SVD", value: "svd" },
          { label: "Cholesky", value: "cholesky" },
          { label: "LSQR", value: "lsqr" },
        ],
      },
    ],
  },
  {
    id: "lasso-regression",
    name: "LASSO Regression",
    shortName: "lasso",
    className: "Lasso",
    type: "regression",
    category: "builtin",
    description: "Linear regression with L1 regularization",
    hyperparameters: [
      {
        name: "alpha",
        label: "Alpha",
        type: "number",
        defaultValue: 1.0,
        placeholder: "Ex. 0.5",
        required: true,
      },
      {
        name: "fit_intercept",
        label: "Fit Intercept",
        type: "select",
        defaultValue: true,
        options: [
          { label: "True", value: true },
          { label: "False", value: false },
        ],
      },
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 1000,
        placeholder: "Ex. 1000",
      },
    ],
  },
  {
    id: "elasticnet-regression",
    name: "ElasticNet Regression",
    shortName: "elasticnet",
    className: "ElasticNet",
    type: "regression",
    category: "builtin",
    description: "Linear regression with L1 and L2 regularization",
    hyperparameters: [
      {
        name: "alpha",
        label: "Alpha",
        type: "number",
        defaultValue: 1.0,
        placeholder: "Ex. 0.5",
        required: true,
      },
      {
        name: "l1_ratio",
        label: "L1 Ratio",
        type: "number",
        defaultValue: 0.5,
        placeholder: "Ex. 0.5",
        required: true,
      },
      {
        name: "fit_intercept",
        label: "Fit Intercept",
        type: "select",
        defaultValue: true,
        options: [
          { label: "True", value: true },
          { label: "False", value: false },
        ],
      },
    ],
  },
  {
    id: "decision-tree",
    name: "Decision Tree",
    shortName: "tree",
    className: "DecisionTreeRegressor",
    type: "regression",
    category: "builtin",
    description: "Decision tree for regression",
    hyperparameters: [
      {
        name: "max_depth",
        label: "Max Depth",
        type: "number",
        defaultValue: null,
        placeholder: "Ex. 10 (optional)",
      },
      {
        name: "min_samples_split",
        label: "Min Samples Split",
        type: "number",
        defaultValue: 2,
        placeholder: "Ex. 2",
      },
      {
        name: "criterion",
        label: "Criterion",
        type: "select",
        defaultValue: "squared_error",
        options: [
          { label: "Squared Error", value: "squared_error" },
          { label: "Friedman MSE", value: "friedman_mse" },
          { label: "Absolute Error", value: "absolute_error" },
        ],
      },
    ],
  },
  {
    id: "random-forest",
    name: "Random Forest",
    shortName: "forest",
    className: "RandomForestRegressor",
    type: "regression",
    category: "builtin",
    description: "Ensemble of decision trees",
    hyperparameters: [
      {
        name: "n_estimators",
        label: "Number of Trees",
        type: "number",
        defaultValue: 100,
        placeholder: "Ex. 100",
        required: true,
      },
      {
        name: "max_depth",
        label: "Max Depth",
        type: "number",
        defaultValue: null,
        placeholder: "Ex. 10 (optional)",
      },
      {
        name: "min_samples_split",
        label: "Min Samples Split",
        type: "number",
        defaultValue: 2,
        placeholder: "Ex. 2",
      },
    ],
  },
  {
    id: "svr",
    name: "Support Vector Regression",
    shortName: "svr",
    className: "SVR",
    type: "regression",
    category: "builtin",
    description: "Support vector machine for regression",
    hyperparameters: [
      {
        name: "kernel",
        label: "Kernel",
        type: "select",
        defaultValue: "rbf",
        options: [
          { label: "RBF", value: "rbf" },
          { label: "Linear", value: "linear" },
          { label: "Poly", value: "poly" },
          { label: "Sigmoid", value: "sigmoid" },
        ],
      },
      {
        name: "C",
        label: "C (Regularization)",
        type: "number",
        defaultValue: 1.0,
        placeholder: "Ex. 1.0",
        required: true,
      },
      {
        name: "epsilon",
        label: "Epsilon",
        type: "number",
        defaultValue: 0.1,
        placeholder: "Ex. 0.1",
      },
    ],
  },
  {
    id: "mlp",
    name: "Multi-Layer Perceptron",
    shortName: "mlp",
    className: "MLPRegressor",
    type: "regression",
    category: "builtin",
    description: "Neural network for regression",
    hyperparameters: [
      {
        name: "hidden_layer_sizes",
        label: "Hidden Layer Sizes",
        type: "text",
        defaultValue: "(100,)",
        placeholder: "Ex. (100, 50)",
        required: true,
      },
      {
        name: "activation",
        label: "Activation",
        type: "select",
        defaultValue: "relu",
        options: [
          { label: "ReLU", value: "relu" },
          { label: "Tanh", value: "tanh" },
          { label: "Logistic", value: "logistic" },
        ],
      },
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 200,
        placeholder: "Ex. 200",
      },
    ],
  },
  {
    id: "knn",
    name: "k-Nearest Neighbours",
    shortName: "knn",
    className: "KNeighborsRegressor",
    type: "regression",
    category: "builtin",
    description: "k-Nearest neighbors for regression",
    hyperparameters: [
      {
        name: "n_neighbors",
        label: "Number of Neighbors",
        type: "number",
        defaultValue: 5,
        placeholder: "Ex. 5",
        required: true,
      },
      {
        name: "weights",
        label: "Weights",
        type: "select",
        defaultValue: "uniform",
        options: [
          { label: "Uniform", value: "uniform" },
          { label: "Distance", value: "distance" },
        ],
      },
      {
        name: "algorithm",
        label: "Algorithm",
        type: "select",
        defaultValue: "auto",
        options: [
          { label: "Auto", value: "auto" },
          { label: "Ball Tree", value: "ball_tree" },
          { label: "KD Tree", value: "kd_tree" },
          { label: "Brute", value: "brute" },
        ],
      },
    ],
  },
];
