import type { AlgorithmCatalogItem } from "../types";

export const ALGORITHMS_CATALOG: AlgorithmCatalogItem[] = [
  {
    id: "linear",
    name: "Linear Regression",
    shortName: "linear",
    className: "LinearRegression",
    type: "regression",
    category: "builtin",
    description: "Linear model for regression problems",
    hyperparameters: [
      {
        name: "fit_intercept",
        label: "Fit Intercept",
        type: "select",
        defaultValue: true,
        options: [
          { label: "True", value: true },
          { label: "False", value: false },
        ],
      },
    ],
  },
  {
    id: "ridge",
    name: "Ridge Regression",
    shortName: "ridge",
    className: "Ridge",
    type: "regression",
    category: "builtin",
    description: "Linear regression with L2 regularization",
    hyperparameters: [
      {
        name: "alpha",
        label: "Alpha",
        type: "number",
        defaultValue: 1.0,
        placeholder: "Ex. 0.5",
      },
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 10000,
        placeholder: "Ex. 10000",
      },
    ],
  },
  {
    id: "lasso",
    name: "LASSO Regression",
    shortName: "lasso",
    className: "Lasso",
    type: "regression",
    category: "builtin",
    description: "Linear regression with L1 regularization",
    hyperparameters: [
      {
        name: "alpha",
        label: "Alpha",
        type: "number",
        defaultValue: 0.1,
        placeholder: "Ex. 0.1",
      },
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 10000,
        placeholder: "Ex. 10000",
      },
    ],
  },
  {
    id: "bridge",
    name: "Bayesian Ridge Regression",
    shortName: "bridge",
    className: "BayesianRidge",
    type: "regression",
    category: "builtin",
    description: "Bayesian ridge regression",
    hyperparameters: [
      {
        name: "alpha_1",
        label: "Alpha 1",
        type: "number",
        defaultValue: 1e-6,
        placeholder: "Ex. 1e-6",
      },
      {
        name: "alpha_2",
        label: "Alpha 2",
        type: "number",
        defaultValue: 1e-6,
        placeholder: "Ex. 1e-6",
      },
      {
        name: "lambda_1",
        label: "Lambda 1",
        type: "number",
        defaultValue: 1e-6,
        placeholder: "Ex. 1e-6",
      },
      {
        name: "lambda_2",
        label: "Lambda 2",
        type: "number",
        defaultValue: 1e-6,
        placeholder: "Ex. 1e-6",
      },
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 10000,
        placeholder: "Ex. 10000",
      },
    ],
  },
  {
    id: "elasticnet",
    name: "Elastic Net Regression",
    shortName: "elasticnet",
    className: "ElasticNet",
    type: "regression",
    category: "builtin",
    description: "Linear regression with L1 and L2 regularization",
    hyperparameters: [
      {
        name: "alpha",
        label: "Alpha",
        type: "number",
        defaultValue: 0.1,
        placeholder: "Ex. 0.1",
      },
      {
        name: "l1_ratio",
        label: "L1 Ratio",
        type: "number",
        defaultValue: 0.5,
        placeholder: "Ex. 0.5",
      },
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 10000,
        placeholder: "Ex. 10000",
      },
    ],
  },
  {
    id: "dtr",
    name: "Decision Tree Regression",
    shortName: "dtr",
    className: "DecisionTreeRegressor",
    type: "regression",
    category: "builtin",
    description: "Decision tree for regression",
    hyperparameters: [
      {
        name: "min_samples_split",
        label: "Min Samples Split",
        type: "number",
        defaultValue: 10,
        placeholder: "Ex. 10",
      },
      {
        name: "criterion",
        label: "Criterion",
        type: "select",
        defaultValue: "squared_error",
        options: [
          { label: "Squared Error", value: "squared_error" },
          { label: "Friedman MSE", value: "friedman_mse" },
          { label: "Absolute Error", value: "absolute_error" },
          { label: "Poisson", value: "poisson" },
        ],
      },
      {
        name: "max_depth",
        label: "Max Depth",
        type: "number",
        defaultValue: null,
        placeholder: "Ex. 10 (optional)",
      },
    ],
  },
  {
    id: "rf",
    name: "Random Forest",
    shortName: "rf",
    className: "RandomForestRegressor",
    type: "regression",
    category: "builtin",
    description: "Ensemble of decision trees for regression",
    hyperparameters: [
      {
        name: "min_samples_split",
        label: "Min Samples Split",
        type: "number",
        defaultValue: 10,
        placeholder: "Ex. 10",
      },
      {
        name: "n_estimators",
        label: "Number of Trees",
        type: "number",
        defaultValue: 100,
        placeholder: "Ex. 100",
      },
      {
        name: "criterion",
        label: "Criterion",
        type: "select",
        defaultValue: "squared_error",
        options: [
          { label: "Friedman MSE", value: "friedman_mse" },
          { label: "Absolute Error", value: "absolute_error" },
          { label: "Poisson", value: "poisson" },
          { label: "Squared Error", value: "squared_error" },
        ],
      },
      {
        name: "max_depth",
        label: "Max Depth",
        type: "number",
        defaultValue: null,
        placeholder: "Ex. 10 (optional)",
      },
    ],
  },
  {
    id: "svr",
    name: "Support Vector Regression",
    shortName: "svr",
    className: "SVR",
    type: "regression",
    category: "builtin",
    description: "Support vector machine for regression",
    hyperparameters: [
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 10000,
        placeholder: "Ex. 10000",
      },
      {
        name: "kernel",
        label: "Kernel",
        type: "select",
        defaultValue: "rbf",
        options: [
          { label: "RBF", value: "rbf" },
          { label: "Linear", value: "linear" },
          { label: "Sigmoid", value: "sigmoid" },
        ],
      },
      {
        name: "C",
        label: "C (Regularization)",
        type: "number",
        defaultValue: 1.0,
        placeholder: "Ex. 1.0",
      },
      {
        name: "gamma",
        label: "Gamma",
        type: "select",
        defaultValue: "scale",
        options: [
          { label: "Scale", value: "scale" },
          { label: "Auto", value: "auto" },
        ],
      },
    ],
  },
  {
    id: "mlp",
    name: "Multi-Layer Perceptron Regression",
    shortName: "mlp",
    className: "MLPRegressor",
    type: "regression",
    category: "builtin",
    description: "Neural network for regression",
    hyperparameters: [
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 20000,
        placeholder: "Ex. 20000",
      },
      {
        name: "hidden_layer_sizes",
        label: "Hidden Layer Sizes",
        type: "text",
        defaultValue: "(100,)",
        placeholder: "Ex. (100, 50)",
      },
      {
        name: "activation",
        label: "Activation",
        type: "select",
        defaultValue: "relu",
        options: [
          { label: "Identity", value: "identity" },
          { label: "Logistic", value: "logistic" },
          { label: "Tanh", value: "tanh" },
          { label: "ReLU", value: "relu" },
        ],
      },
      {
        name: "alpha",
        label: "Alpha",
        type: "number",
        defaultValue: 0.0001,
        placeholder: "Ex. 0.0001",
      },
      {
        name: "learning_rate",
        label: "Learning Rate",
        type: "select",
        defaultValue: "constant",
        options: [
          { label: "Constant", value: "constant" },
          { label: "Invscaling", value: "invscaling" },
          { label: "Adaptive", value: "adaptive" },
        ],
      },
    ],
  },
  {
    id: "knn",
    name: "K-Nearest Neighbour Regression",
    shortName: "knn",
    className: "KNeighborsRegressor",
    type: "regression",
    category: "builtin",
    description: "k-Nearest neighbors for regression",
    hyperparameters: [
      {
        name: "n_neighbors",
        label: "Number of Neighbors",
        type: "number",
        defaultValue: 5,
        placeholder: "Ex. 5",
      },
      {
        name: "weights",
        label: "Weights",
        type: "select",
        defaultValue: "uniform",
        options: [
          { label: "Uniform", value: "uniform" },
          { label: "Distance", value: "distance" },
        ],
      },
      {
        name: "algorithm",
        label: "Algorithm",
        type: "select",
        defaultValue: "auto",
        options: [
          { label: "Auto", value: "auto" },
          { label: "Ball Tree", value: "ball_tree" },
          { label: "KD Tree", value: "kd_tree" },
          { label: "Brute", value: "brute" },
        ],
      },
      {
        name: "leaf_size",
        label: "Leaf Size",
        type: "number",
        defaultValue: 30,
        placeholder: "Ex. 30",
      },
    ],
  },
  {
    id: "logistic",
    name: "Logistic Regression",
    shortName: "logistic",
    className: "LogisticRegression",
    type: "classification",
    category: "builtin",
    description: "Logistic regression for classification",
    hyperparameters: [
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 10000,
        placeholder: "Ex. 10000",
      },
      {
        name: "C",
        label: "C (Inverse Regularization)",
        type: "number",
        defaultValue: 1.0,
        placeholder: "Ex. 1.0",
      },
    ],
  },
  {
    id: "svc",
    name: "Support Vector Classifier",
    shortName: "svc",
    className: "SVC",
    type: "classification",
    category: "builtin",
    description: "Support vector machine for classification",
    hyperparameters: [
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 10000,
        placeholder: "Ex. 10000",
      },
      {
        name: "kernel",
        label: "Kernel",
        type: "select",
        defaultValue: "rbf",
        options: [
          { label: "Linear", value: "linear" },
          { label: "RBF", value: "rbf" },
          { label: "Sigmoid", value: "sigmoid" },
        ],
      },
      {
        name: "C",
        label: "C (Regularization)",
        type: "number",
        defaultValue: 1.0,
        placeholder: "Ex. 1.0",
      },
      {
        name: "gamma",
        label: "Gamma",
        type: "select",
        defaultValue: "scale",
        options: [
          { label: "Scale", value: "scale" },
          { label: "Auto", value: "auto" },
        ],
      },
    ],
  },
  {
    id: "knn_classifier",
    name: "k-Nearest Neighbours Classifier",
    shortName: "knn_classifier",
    className: "KNeighborsClassifier",
    type: "classification",
    category: "builtin",
    description: "k-Nearest neighbors for classification",
    hyperparameters: [
      {
        name: "n_neighbors",
        label: "Number of Neighbors",
        type: "number",
        defaultValue: 5,
        placeholder: "Ex. 5",
      },
      {
        name: "weights",
        label: "Weights",
        type: "select",
        defaultValue: "uniform",
        options: [
          { label: "Uniform", value: "uniform" },
          { label: "Distance", value: "distance" },
        ],
      },
      {
        name: "algorithm",
        label: "Algorithm",
        type: "select",
        defaultValue: "auto",
        options: [
          { label: "Auto", value: "auto" },
          { label: "Ball Tree", value: "ball_tree" },
          { label: "KD Tree", value: "kd_tree" },
          { label: "Brute", value: "brute" },
        ],
      },
      {
        name: "leaf_size",
        label: "Leaf Size",
        type: "number",
        defaultValue: 30,
        placeholder: "Ex. 30",
      },
    ],
  },
  {
    id: "dtc",
    name: "Decision Tree Classifier",
    shortName: "dtc",
    className: "DecisionTreeClassifier",
    type: "classification",
    category: "builtin",
    description: "Decision tree for classification",
    hyperparameters: [
      {
        name: "min_samples_split",
        label: "Min Samples Split",
        type: "number",
        defaultValue: 10,
        placeholder: "Ex. 10",
      },
      {
        name: "criterion",
        label: "Criterion",
        type: "select",
        defaultValue: "gini",
        options: [
          { label: "Gini", value: "gini" },
          { label: "Entropy", value: "entropy" },
          { label: "Log Loss", value: "log_loss" },
        ],
      },
      {
        name: "max_depth",
        label: "Max Depth",
        type: "number",
        defaultValue: null,
        placeholder: "Ex. 10 (optional)",
      },
    ],
  },
  {
    id: "rf_classifier",
    name: "Random Forest Classifier",
    shortName: "rf_classifier",
    className: "RandomForestClassifier",
    type: "classification",
    category: "builtin",
    description: "Ensemble of decision trees for classification",
    hyperparameters: [
      {
        name: "min_samples_split",
        label: "Min Samples Split",
        type: "number",
        defaultValue: 10,
        placeholder: "Ex. 10",
      },
      {
        name: "n_estimators",
        label: "Number of Trees",
        type: "number",
        defaultValue: 100,
        placeholder: "Ex. 100",
      },
      {
        name: "criterion",
        label: "Criterion",
        type: "select",
        defaultValue: "gini",
        options: [
          { label: "Gini", value: "gini" },
          { label: "Entropy", value: "entropy" },
          { label: "Log Loss", value: "log_loss" },
        ],
      },
      {
        name: "max_depth",
        label: "Max Depth",
        type: "number",
        defaultValue: null,
        placeholder: "Ex. 10 (optional)",
      },
    ],
  },
  {
    id: "gaussian_nb",
    name: "Gaussian Naive Bayes",
    shortName: "gaussian_nb",
    className: "GaussianNB",
    type: "classification",
    category: "builtin",
    description: "Gaussian Naive Bayes classifier",
    hyperparameters: [
      {
        name: "var_smoothing",
        label: "Var Smoothing",
        type: "number",
        defaultValue: 1e-9,
        placeholder: "Ex. 1e-9",
      },
    ],
  },
  {
    id: "ridge_classifier",
    name: "Ridge Classifier",
    shortName: "ridge_classifier",
    className: "RidgeClassifier",
    type: "classification",
    category: "builtin",
    description: "Ridge classifier",
    hyperparameters: [
      {
        name: "max_iter",
        label: "Max Iterations",
        type: "number",
        defaultValue: 10000,
        placeholder: "Ex. 10000",
      },
      {
        name: "alpha",
        label: "Alpha",
        type: "number",
        defaultValue: 1.0,
        placeholder: "Ex. 1.0",
      },
    ],
  },
];
