export { Algorithms } from './Algorithms/Algorithms'
export { Database } from './Database/Database'
export { Edit } from './Edit/Edit'
export { Experiments } from './Experiments/Experiments'
export { Files } from './Files/Files'
export { Home } from './Home/Home'
export { IconComponentNode } from './IconComponentNode/IconComponentNode'
export { Metrics } from './Metrics/Metrics'
export { Results } from './Results/Results'
export { Save } from './Save/Save'

